version: "3"
services:
  dev:
    env_file: .env
    user: ${USER_NAME}
    build:
      args:
        - username=${USER_NAME}
        - userhome=${USER_HOME}
      context: .
      # Location is relative to folder containing this compose file
      dockerfile: Dockerfile
    volumes:
      # This lets you avoid setting up Git again in the container
      - ~/.gitconfig:${USER_HOME}/.gitconfig

      # Mount configuration settings to configure vscode-remote
      - ./settings.vscode.json:${USER_HOME}/.vscode-remote/data/Machine/settings.json

      # Mounts the tox project folder to '/workspace'. We'll then reference this as the
      # workspaceFolder in '.devcontainer.json' so VS Code starts here.
      - ${TOX_PROJECT_DIR}:/workspace

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity